### ISSUE TITLE
#bug while !kang

### ISSUE THREAD

**Issue by sunilroyy007** [AbirHasan2005/Forward-Client#13]
2021-09-30T14:57:31.942014+00:00 app[worker.1]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-09-30T14:57:31.942028+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-09-30T14:57:31.942028+00:00 app[worker.1]: 
2021-09-30T14:57:52.205792+00:00 app[worker.1]: 'NoneType' object has no attribute 'id'
2021-09-30T14:57:52.205807+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-30T14:57:52.205809+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-09-30T14:57:52.205809+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-09-30T14:57:52.205809+00:00 app[worker.1]:   File "/app/main.py", line 50, in main
2021-09-30T14:57:52.205810+00:00 app[worker.1]:     elif (message.text == "!kang") and (message.from_user.id == (await client.get_me()).id):
2021-09-30T14:57:52.205811+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'id'

https://extraimages.net/image/taZoh
https://extraimages.net/image/tazmk
https://extraimages.net/image/taBkR

i was trying to do !kang whole channel but it gives that error. not edited anything directly deployed from your repo

 once check images it shows it links successfully FORWARD_FROM_CHAT_ID id but  FORWARD_TO_CHAT_ID says none . i cross-checked ids and they are good 

i tried do kang in a test channel with 10 videos and it still failed

**Comment by AbirHasan2005** [comment]
Are you anonymus admin in the chat??

**Comment by sunilroyy007** [comment]
> Are you anonymus admin in the chat??

nope i was transfering channel to channel not groups. i used !kang in channel but it doesn't respond so i tried in bot 😂 . empty bot

**Comment by AbirHasan2005** [comment]
Do in your Saved Messages.
